// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: MQOne

#include "../ui.h"


// COMPONENT MenuButton

lv_obj_t * ui_Button_MenuButton_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Button_MenuButton;
    cui_Button_MenuButton = lv_button_create(comp_parent);
    lv_obj_set_height(cui_Button_MenuButton, 50);
    lv_obj_set_width(cui_Button_MenuButton, lv_pct(90));
    lv_obj_set_x(cui_Button_MenuButton, -53);
    lv_obj_set_y(cui_Button_MenuButton, -168);
    lv_obj_set_align(cui_Button_MenuButton, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_Button_MenuButton, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(cui_Button_MenuButton, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(cui_Button_MenuButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(cui_Button_MenuButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_Button_MenuButton, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(cui_Button_MenuButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Background2);
    ui_object_set_themeable_style_property(cui_Button_MenuButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Background2);
    lv_obj_set_style_border_color(cui_Button_MenuButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_Button_MenuButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cui_Button_MenuButton, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Label_Label3;
    cui_Label_Label3 = lv_label_create(cui_Button_MenuButton);
    lv_obj_set_width(cui_Label_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_Label_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Label_Label3, "Demo");
    ui_object_set_themeable_style_property(cui_Label_Label3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Font);
    ui_object_set_themeable_style_property(cui_Label_Label3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Font);
    lv_obj_set_style_text_font(cui_Label_Label3, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_BUTTON_MENUBUTTON_NUM);
    children[UI_COMP_BUTTON_MENUBUTTON_BUTTON_MENUBUTTON] = cui_Button_MenuButton;
    children[UI_COMP_BUTTON_MENUBUTTON_LABEL_LABEL3] = cui_Label_Label3;
    lv_obj_add_event_cb(cui_Button_MenuButton, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Button_MenuButton, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Button_MenuButton_create_hook(cui_Button_MenuButton);
    return cui_Button_MenuButton;
}

