// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: MQOne

#ifndef _UI_COMP_MENUBUTTON_H
#define _UI_COMP_MENUBUTTON_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT MenuButton
#define UI_COMP_BUTTON_MENUBUTTON_BUTTON_MENUBUTTON 0
#define UI_COMP_BUTTON_MENUBUTTON_LABEL_LABEL3 1
#define _UI_COMP_BUTTON_MENUBUTTON_NUM 2
lv_obj_t * ui_Button_MenuButton_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
