// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: MQOne

#include "../ui.h"

void ui_comp_Panel_Panel_create_hook(lv_obj_t * comp) {}

void ui_comp_Button_MenuButton_create_hook(lv_obj_t * comp) {}
