// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: MQOne

#include "../ui.h"

void ui_Camera_Module_screen_init(void)
{
    ui_Camera_Module = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Camera_Module, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Camera_Module, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Background);
    ui_object_set_themeable_style_property(ui_Camera_Module, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Background);

    ui_Camera_Module_Button_Button5 = lv_button_create(ui_Camera_Module);
    lv_obj_set_width(ui_Camera_Module_Button_Button5, 216);
    lv_obj_set_height(ui_Camera_Module_Button_Button5, 30);
    lv_obj_set_x(ui_Camera_Module_Button_Button5, lv_pct(0));
    lv_obj_set_y(ui_Camera_Module_Button_Button5, lv_pct(-43));
    lv_obj_set_align(ui_Camera_Module_Button_Button5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Camera_Module_Button_Button5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Camera_Module_Button_Button5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Camera_Module_Button_Button5, lv_color_hex(0x666563), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Camera_Module_Button_Button5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Camera_Module_Button_Button5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Camera_Module_Button_Button5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Camera_Module_Button_Button5, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Camera_Module_Label_Label6 = lv_label_create(ui_Camera_Module_Button_Button5);
    lv_obj_set_width(ui_Camera_Module_Label_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Camera_Module_Label_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Camera_Module_Label_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Camera_Module_Label_Label6, "< Back");
    ui_object_set_themeable_style_property(ui_Camera_Module_Label_Label6, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_COLOR, _ui_theme_color_Font);
    ui_object_set_themeable_style_property(ui_Camera_Module_Label_Label6, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_OPA, _ui_theme_alpha_Font);
    lv_obj_set_style_text_font(ui_Camera_Module_Label_Label6, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Camera_Module_Button_Button5, ui_event_Camera_Module_Button_Button5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Camera_Module, ui_event_Camera_Module, LV_EVENT_ALL, NULL);

}
