// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: MQOne

#include "../ui.h"

void ui_Dev_Module_screen_init(void)
{
    ui_Dev_Module = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Dev_Module, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Dev_Module, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Background);
    ui_object_set_themeable_style_property(ui_Dev_Module, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Background);

    ui_Dev_Module_Button_Button7 = lv_button_create(ui_Dev_Module);
    lv_obj_set_height(ui_Dev_Module_Button_Button7, 30);
    lv_obj_set_width(ui_Dev_Module_Button_Button7, lv_pct(90));
    lv_obj_set_x(ui_Dev_Module_Button_Button7, lv_pct(0));
    lv_obj_set_y(ui_Dev_Module_Button_Button7, lv_pct(-43));
    lv_obj_set_align(ui_Dev_Module_Button_Button7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dev_Module_Button_Button7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Dev_Module_Button_Button7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Dev_Module_Button_Button7, lv_color_hex(0x666563), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Dev_Module_Button_Button7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Dev_Module_Button_Button7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Dev_Module_Button_Button7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Dev_Module_Button_Button7, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Dev_Module_Label_Label8 = lv_label_create(ui_Dev_Module_Button_Button7);
    lv_obj_set_width(ui_Dev_Module_Label_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Dev_Module_Label_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Dev_Module_Label_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Dev_Module_Label_Label8, "< Back");
    ui_object_set_themeable_style_property(ui_Dev_Module_Label_Label8, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Font);
    ui_object_set_themeable_style_property(ui_Dev_Module_Label_Label8, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Font);
    lv_obj_set_style_text_font(ui_Dev_Module_Label_Label8, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Dev_Module_Panel_Panel1 = lv_obj_create(ui_Dev_Module);
    lv_obj_set_width(ui_Dev_Module_Panel_Panel1, 100);
    lv_obj_set_height(ui_Dev_Module_Panel_Panel1, 206);
    lv_obj_set_x(ui_Dev_Module_Panel_Panel1, 0);
    lv_obj_set_y(ui_Dev_Module_Panel_Panel1, 30);
    lv_obj_set_align(ui_Dev_Module_Panel_Panel1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Dev_Module_Panel_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Dev_Module_Panel_Panel1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Background2);
    ui_object_set_themeable_style_property(ui_Dev_Module_Panel_Panel1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Background2);

    ui_Dev_Module_Label_Label11 = lv_label_create(ui_Dev_Module);
    lv_obj_set_width(ui_Dev_Module_Label_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Dev_Module_Label_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dev_Module_Label_Label11, 0);
    lv_obj_set_y(ui_Dev_Module_Label_Label11, -100);
    lv_obj_set_align(ui_Dev_Module_Label_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Dev_Module_Label_Label11, "GPIO Status");
    lv_obj_set_style_text_font(ui_Dev_Module_Label_Label11, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Dev_Module_Button_Button7, ui_event_Dev_Module_Button_Button7, LV_EVENT_ALL, NULL);

}
