// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: MQOne

#include "../ui.h"

void ui_Mountain_Module_screen_init(void)
{
    ui_Mountain_Module = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Mountain_Module, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Mountain_Module, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Background);
    ui_object_set_themeable_style_property(ui_Mountain_Module, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Background);

    ui_Mountain_Module_Button_Button6 = lv_button_create(ui_Mountain_Module);
    lv_obj_set_height(ui_Mountain_Module_Button_Button6, 30);
    lv_obj_set_width(ui_Mountain_Module_Button_Button6, lv_pct(90));
    lv_obj_set_x(ui_Mountain_Module_Button_Button6, lv_pct(0));
    lv_obj_set_y(ui_Mountain_Module_Button_Button6, lv_pct(-43));
    lv_obj_set_align(ui_Mountain_Module_Button_Button6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Mountain_Module_Button_Button6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Mountain_Module_Button_Button6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Mountain_Module_Button_Button6, lv_color_hex(0x666563), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Mountain_Module_Button_Button6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Mountain_Module_Button_Button6, lv_color_hex(0x000000),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Mountain_Module_Button_Button6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Mountain_Module_Button_Button6, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Mountain_Module_Label_Label7 = lv_label_create(ui_Mountain_Module_Button_Button6);
    lv_obj_set_width(ui_Mountain_Module_Label_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Mountain_Module_Label_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Mountain_Module_Label_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Mountain_Module_Label_Label7, "< Back");
    ui_object_set_themeable_style_property(ui_Mountain_Module_Label_Label7, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_COLOR, _ui_theme_color_Font);
    ui_object_set_themeable_style_property(ui_Mountain_Module_Label_Label7, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_OPA, _ui_theme_alpha_Font);
    lv_obj_set_style_text_font(ui_Mountain_Module_Label_Label7, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Mountain_Module_Image_Image5 = lv_image_create(ui_Mountain_Module);
    lv_image_set_src(ui_Mountain_Module_Image_Image5, &ui_img_sat_png);
    lv_obj_set_width(ui_Mountain_Module_Image_Image5, LV_SIZE_CONTENT);   /// 512
    lv_obj_set_height(ui_Mountain_Module_Image_Image5, LV_SIZE_CONTENT);    /// 512
    lv_obj_set_x(ui_Mountain_Module_Image_Image5, 0);
    lv_obj_set_y(ui_Mountain_Module_Image_Image5, 20);
    lv_obj_set_align(ui_Mountain_Module_Image_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Mountain_Module_Image_Image5, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Mountain_Module_Image_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Mountain_Module_Image_Image5, 45);

    ui_Mountain_Module_Container_Container3 = lv_obj_create(ui_Mountain_Module);
    lv_obj_remove_style_all(ui_Mountain_Module_Container_Container3);
    lv_obj_set_width(ui_Mountain_Module_Container_Container3, LV_SIZE_CONTENT);   /// 163
    lv_obj_set_height(ui_Mountain_Module_Container_Container3, LV_SIZE_CONTENT);    /// 119
    lv_obj_set_x(ui_Mountain_Module_Container_Container3, 13);
    lv_obj_set_y(ui_Mountain_Module_Container_Container3, 240);
    lv_obj_set_flex_flow(ui_Mountain_Module_Container_Container3, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Mountain_Module_Container_Container3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START,
                          LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Mountain_Module_Container_Container3,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Mountain_Module_Label_Label9 = lv_label_create(ui_Mountain_Module_Container_Container3);
    lv_obj_set_width(ui_Mountain_Module_Label_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Mountain_Module_Label_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Mountain_Module_Label_Label9, -30);
    lv_obj_set_y(ui_Mountain_Module_Label_Label9, 110);
    lv_obj_set_align(ui_Mountain_Module_Label_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Mountain_Module_Label_Label9, "Temperature:");
    lv_obj_set_style_text_font(ui_Mountain_Module_Label_Label9, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Mountain_Module_Label_Label12 = lv_label_create(ui_Mountain_Module_Container_Container3);
    lv_obj_set_width(ui_Mountain_Module_Label_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Mountain_Module_Label_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Mountain_Module_Label_Label12, -30);
    lv_obj_set_y(ui_Mountain_Module_Label_Label12, 110);
    lv_obj_set_align(ui_Mountain_Module_Label_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Mountain_Module_Label_Label12, "Humidity:");
    lv_obj_set_style_text_font(ui_Mountain_Module_Label_Label12, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Mountain_Module_Label_Label13 = lv_label_create(ui_Mountain_Module_Container_Container3);
    lv_obj_set_width(ui_Mountain_Module_Label_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Mountain_Module_Label_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Mountain_Module_Label_Label13, -30);
    lv_obj_set_y(ui_Mountain_Module_Label_Label13, 110);
    lv_obj_set_align(ui_Mountain_Module_Label_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Mountain_Module_Label_Label13, "Preassure:");
    lv_obj_set_style_text_font(ui_Mountain_Module_Label_Label13, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Mountain_Module_Container_Container4 = lv_obj_create(ui_Mountain_Module);
    lv_obj_remove_style_all(ui_Mountain_Module_Container_Container4);
    lv_obj_set_width(ui_Mountain_Module_Container_Container4, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Mountain_Module_Container_Container4, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Mountain_Module_Container_Container4, -13);
    lv_obj_set_y(ui_Mountain_Module_Container_Container4, 240);
    lv_obj_set_align(ui_Mountain_Module_Container_Container4, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_flex_flow(ui_Mountain_Module_Container_Container4, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Mountain_Module_Container_Container4, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_END,
                          LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Mountain_Module_Container_Container4,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Mountain_Module_Label_Label10 = lv_label_create(ui_Mountain_Module_Container_Container4);
    lv_obj_set_width(ui_Mountain_Module_Label_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Mountain_Module_Label_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Mountain_Module_Label_Label10, 63);
    lv_obj_set_y(ui_Mountain_Module_Label_Label10, 89);
    lv_obj_set_align(ui_Mountain_Module_Label_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Mountain_Module_Label_Label10, "");
    lv_obj_set_style_text_font(ui_Mountain_Module_Label_Label10, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Mountain_Module_Label_Label14 = lv_label_create(ui_Mountain_Module_Container_Container4);
    lv_obj_set_width(ui_Mountain_Module_Label_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Mountain_Module_Label_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Mountain_Module_Label_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Mountain_Module_Label_Label14, "");
    lv_obj_set_style_text_font(ui_Mountain_Module_Label_Label14, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Mountain_Module_Label_Label15 = lv_label_create(ui_Mountain_Module_Container_Container4);
    lv_obj_set_width(ui_Mountain_Module_Label_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Mountain_Module_Label_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Mountain_Module_Label_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Mountain_Module_Label_Label15, "");
    lv_obj_set_style_text_font(ui_Mountain_Module_Label_Label15, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Mountain_Module_Container_Container7 = lv_obj_create(ui_Mountain_Module);
    lv_obj_remove_style_all(ui_Mountain_Module_Container_Container7);
    lv_obj_set_height(ui_Mountain_Module_Container_Container7, 50);
    lv_obj_set_width(ui_Mountain_Module_Container_Container7, lv_pct(100));
    lv_obj_set_x(ui_Mountain_Module_Container_Container7, 0);
    lv_obj_set_y(ui_Mountain_Module_Container_Container7, -90);
    lv_obj_set_align(ui_Mountain_Module_Container_Container7, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Mountain_Module_Container_Container7, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Mountain_Module_Container_Container7, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Mountain_Module_Container_Container7,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Mountain_Module_Label_Label4 = lv_label_create(ui_Mountain_Module_Container_Container7);
    lv_obj_set_width(ui_Mountain_Module_Label_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Mountain_Module_Label_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Mountain_Module_Label_Label4, 0);
    lv_obj_set_y(ui_Mountain_Module_Label_Label4, -105);
    lv_obj_set_align(ui_Mountain_Module_Label_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Mountain_Module_Label_Label4, "Coordinates");
    lv_obj_set_style_text_font(ui_Mountain_Module_Label_Label4, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Mountain_Module_Label_Label4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Mountain_Module_Label_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Mountain_Module_Label_Label4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Mountain_Module_Label_Label4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Mountain_Module_Label_Label4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Mountain_Module_Label_Label4, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Mountain_Module_Label_Label18 = lv_label_create(ui_Mountain_Module_Container_Container7);
    lv_obj_set_width(ui_Mountain_Module_Label_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Mountain_Module_Label_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Mountain_Module_Label_Label18, 0);
    lv_obj_set_y(ui_Mountain_Module_Label_Label18, -105);
    lv_obj_set_align(ui_Mountain_Module_Label_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Mountain_Module_Label_Label18, "-");
    lv_obj_set_style_text_font(ui_Mountain_Module_Label_Label18, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Mountain_Module_Label_Label18, lv_color_hex(0x000000),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Mountain_Module_Label_Label18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Mountain_Module_Label_Label18, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Mountain_Module_Label_Label18, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Mountain_Module_Label_Label18, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Mountain_Module_Label_Label18, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Mountain_Module_Container_Container5 = lv_obj_create(ui_Mountain_Module);
    lv_obj_remove_style_all(ui_Mountain_Module_Container_Container5);
    lv_obj_set_width(ui_Mountain_Module_Container_Container5, lv_pct(100));
    lv_obj_set_height(ui_Mountain_Module_Container_Container5, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Mountain_Module_Container_Container5, 0);
    lv_obj_set_y(ui_Mountain_Module_Container_Container5, -50);
    lv_obj_set_align(ui_Mountain_Module_Container_Container5, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Mountain_Module_Container_Container5, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Mountain_Module_Container_Container5, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START,
                          LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Mountain_Module_Container_Container5,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Mountain_Module_Container_Container8 = lv_obj_create(ui_Mountain_Module_Container_Container5);
    lv_obj_remove_style_all(ui_Mountain_Module_Container_Container8);
    lv_obj_set_width(ui_Mountain_Module_Container_Container8, lv_pct(50));
    lv_obj_set_height(ui_Mountain_Module_Container_Container8, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_Mountain_Module_Container_Container8, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Mountain_Module_Container_Container8, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Mountain_Module_Container_Container8, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START,
                          LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Mountain_Module_Container_Container8,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Mountain_Module_Container_Container8, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Mountain_Module_Container_Container8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Mountain_Module_Container_Container8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Mountain_Module_Container_Container8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Mountain_Module_Label_Label16 = lv_label_create(ui_Mountain_Module_Container_Container8);
    lv_obj_set_width(ui_Mountain_Module_Label_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Mountain_Module_Label_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Mountain_Module_Label_Label16, -61);
    lv_obj_set_y(ui_Mountain_Module_Label_Label16, -60);
    lv_obj_set_align(ui_Mountain_Module_Label_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Mountain_Module_Label_Label16, "Alt: ");
    lv_obj_set_style_text_font(ui_Mountain_Module_Label_Label16, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Mountain_Module_Label_Label20 = lv_label_create(ui_Mountain_Module_Container_Container8);
    lv_obj_set_width(ui_Mountain_Module_Label_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Mountain_Module_Label_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Mountain_Module_Label_Label20, -61);
    lv_obj_set_y(ui_Mountain_Module_Label_Label20, -60);
    lv_obj_set_align(ui_Mountain_Module_Label_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Mountain_Module_Label_Label20, "-");
    lv_obj_set_style_text_font(ui_Mountain_Module_Label_Label20, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Mountain_Module_Container_Container9 = lv_obj_create(ui_Mountain_Module_Container_Container5);
    lv_obj_remove_style_all(ui_Mountain_Module_Container_Container9);
    lv_obj_set_height(ui_Mountain_Module_Container_Container9, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_flex_grow(ui_Mountain_Module_Container_Container9, 1);
    lv_obj_set_align(ui_Mountain_Module_Container_Container9, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Mountain_Module_Container_Container9, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Mountain_Module_Container_Container9, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START,
                          LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Mountain_Module_Container_Container9,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Mountain_Module_Container_Container9, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Mountain_Module_Container_Container9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Mountain_Module_Container_Container9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Mountain_Module_Container_Container9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Mountain_Module_Label_Label21 = lv_label_create(ui_Mountain_Module_Container_Container9);
    lv_obj_set_width(ui_Mountain_Module_Label_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Mountain_Module_Label_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Mountain_Module_Label_Label21, -61);
    lv_obj_set_y(ui_Mountain_Module_Label_Label21, -60);
    lv_obj_set_align(ui_Mountain_Module_Label_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Mountain_Module_Label_Label21, "Sat Fix: ");
    lv_obj_set_style_text_font(ui_Mountain_Module_Label_Label21, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Mountain_Module_Label_Label22 = lv_label_create(ui_Mountain_Module_Container_Container9);
    lv_obj_set_width(ui_Mountain_Module_Label_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Mountain_Module_Label_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Mountain_Module_Label_Label22, -61);
    lv_obj_set_y(ui_Mountain_Module_Label_Label22, -60);
    lv_obj_set_align(ui_Mountain_Module_Label_Label22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Mountain_Module_Label_Label22, "0");
    lv_obj_set_style_text_font(ui_Mountain_Module_Label_Label22, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Mountain_Module_Button_Button6, ui_event_Mountain_Module_Button_Button6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Mountain_Module, ui_event_Mountain_Module, LV_EVENT_ALL, NULL);

}
