// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: MQOne

#include "../ui.h"

void ui_Screen_Start_App_screen_init(void)
{
    ui_Screen_Start_App = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen_Start_App, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_Screen_Start_App, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Screen_Start_App, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    ui_object_set_themeable_style_property(ui_Screen_Start_App, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Background);
    ui_object_set_themeable_style_property(ui_Screen_Start_App, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Background);

    ui_Screen_Start_App_Image_MQLogo = lv_image_create(ui_Screen_Start_App);
    lv_image_set_src(ui_Screen_Start_App_Image_MQLogo, &ui_img_mq_png);
    lv_obj_set_width(ui_Screen_Start_App_Image_MQLogo, LV_SIZE_CONTENT);   /// 182
    lv_obj_set_height(ui_Screen_Start_App_Image_MQLogo, LV_SIZE_CONTENT);    /// 76
    lv_obj_set_x(ui_Screen_Start_App_Image_MQLogo, 0);
    lv_obj_set_y(ui_Screen_Start_App_Image_MQLogo, -30);
    lv_obj_set_align(ui_Screen_Start_App_Image_MQLogo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen_Start_App_Image_MQLogo, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Screen_Start_App_Image_MQLogo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Screen_Start_App_Spinner_Load = lv_spinner_create(ui_Screen_Start_App);
    //lv_spinner_set_anim_params(ui_Screen_Start_App_Spinner_Load, 1000, 90);
    lv_obj_set_width(ui_Screen_Start_App_Spinner_Load, 40);
    lv_obj_set_height(ui_Screen_Start_App_Spinner_Load, 40);
    lv_obj_set_x(ui_Screen_Start_App_Spinner_Load, 0);
    lv_obj_set_y(ui_Screen_Start_App_Spinner_Load, 90);
    lv_obj_set_align(ui_Screen_Start_App_Spinner_Load, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Screen_Start_App_Spinner_Load, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_opa(ui_Screen_Start_App_Spinner_Load, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Screen_Start_App_Spinner_Load, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Screen_Start_App_Spinner_Load, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_width(ui_Screen_Start_App_Spinner_Load, 8, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Screen_Start_App_Button_Button2 = lv_button_create(ui_Screen_Start_App);
    lv_obj_set_width(ui_Screen_Start_App_Button_Button2, 100);
    lv_obj_set_height(ui_Screen_Start_App_Button_Button2, 50);
    lv_obj_set_x(ui_Screen_Start_App_Button_Button2, 19);
    lv_obj_set_y(ui_Screen_Start_App_Button_Button2, -19);
    lv_obj_set_align(ui_Screen_Start_App_Button_Button2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Screen_Start_App_Button_Button2, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Screen_Start_App_Button_Button2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen_Start_App_Button_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Screen_Start_App_Button_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Screen_Start_App_Button_Button2, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_COLOR, _ui_theme_color_Background2);
    ui_object_set_themeable_style_property(ui_Screen_Start_App_Button_Button2, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_OPA, _ui_theme_alpha_Background2);
    lv_obj_set_style_border_color(ui_Screen_Start_App_Button_Button2, lv_color_hex(0x000000),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Screen_Start_App_Button_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Screen_Start_App_Button_Button2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen_Start_App_Label_Label1 = lv_label_create(ui_Screen_Start_App_Button_Button2);
    lv_obj_set_width(ui_Screen_Start_App_Label_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen_Start_App_Label_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen_Start_App_Label_Label1, 4);
    lv_obj_set_y(ui_Screen_Start_App_Label_Label1, 61);
    lv_obj_set_align(ui_Screen_Start_App_Label_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen_Start_App_Label_Label1, "Inicio");
    ui_object_set_themeable_style_property(ui_Screen_Start_App_Label_Label1, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_COLOR, _ui_theme_color_Font);
    ui_object_set_themeable_style_property(ui_Screen_Start_App_Label_Label1, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_OPA, _ui_theme_alpha_Font);
    lv_obj_set_style_text_font(ui_Screen_Start_App_Label_Label1, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Screen_Start_App_Button_Button2, ui_event_Screen_Start_App_Button_Button2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen_Start_App, ui_event_Screen_Start_App, LV_EVENT_ALL, NULL);

}
