// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: MQOne

#include "../ui.h"

void ui_Screen_Neopixel_screen_init(void)
{
    ui_Screen_Neopixel = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen_Neopixel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Screen_Neopixel_Button_Button9 = lv_button_create(ui_Screen_Neopixel);
    lv_obj_set_height(ui_Screen_Neopixel_Button_Button9, 30);
    lv_obj_set_width(ui_Screen_Neopixel_Button_Button9, lv_pct(90));
    lv_obj_set_x(ui_Screen_Neopixel_Button_Button9, lv_pct(0));
    lv_obj_set_y(ui_Screen_Neopixel_Button_Button9, lv_pct(-43));
    lv_obj_set_align(ui_Screen_Neopixel_Button_Button9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen_Neopixel_Button_Button9, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Screen_Neopixel_Button_Button9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen_Neopixel_Button_Button9, lv_color_hex(0x666563), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen_Neopixel_Button_Button9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Screen_Neopixel_Button_Button9, lv_color_hex(0x000000),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Screen_Neopixel_Button_Button9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Screen_Neopixel_Button_Button9, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen_Neopixel_Label_Label23 = lv_label_create(ui_Screen_Neopixel_Button_Button9);
    lv_obj_set_width(ui_Screen_Neopixel_Label_Label23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen_Neopixel_Label_Label23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Screen_Neopixel_Label_Label23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen_Neopixel_Label_Label23, "< Back");
    ui_object_set_themeable_style_property(ui_Screen_Neopixel_Label_Label23, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_COLOR, _ui_theme_color_Font);
    ui_object_set_themeable_style_property(ui_Screen_Neopixel_Label_Label23, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_OPA, _ui_theme_alpha_Font);
    lv_obj_set_style_text_font(ui_Screen_Neopixel_Label_Label23, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen_Neopixel_Arc_Arc1 = lv_arc_create(ui_Screen_Neopixel);
    lv_obj_set_width(ui_Screen_Neopixel_Arc_Arc1, 150);
    lv_obj_set_height(ui_Screen_Neopixel_Arc_Arc1, 150);
    lv_obj_set_x(ui_Screen_Neopixel_Arc_Arc1, 0);
    lv_obj_set_y(ui_Screen_Neopixel_Arc_Arc1, 40);
    lv_obj_set_align(ui_Screen_Neopixel_Arc_Arc1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen_Neopixel_Arc_Arc1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_Screen_Neopixel_Arc_Arc1, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_arc_set_range(ui_Screen_Neopixel_Arc_Arc1, 0, 23);
    lv_arc_set_value(ui_Screen_Neopixel_Arc_Arc1, 0);
    lv_arc_set_bg_angles(ui_Screen_Neopixel_Arc_Arc1, 0, 360);
    lv_arc_set_mode(ui_Screen_Neopixel_Arc_Arc1, LV_ARC_MODE_REVERSE);
    lv_arc_set_rotation(ui_Screen_Neopixel_Arc_Arc1, 270);
    lv_obj_set_style_arc_width(ui_Screen_Neopixel_Arc_Arc1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Screen_Neopixel_Arc_Arc1, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Screen_Neopixel_Arc_Arc1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Screen_Neopixel_Arc_Arc1, 20, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Screen_Neopixel_Arc_Arc1, lv_color_hex(0xFF0000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen_Neopixel_Arc_Arc1, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Screen_Neopixel_Arc_Arc3 = lv_arc_create(ui_Screen_Neopixel);
    lv_obj_set_width(ui_Screen_Neopixel_Arc_Arc3, 150);
    lv_obj_set_height(ui_Screen_Neopixel_Arc_Arc3, 150);
    lv_obj_set_x(ui_Screen_Neopixel_Arc_Arc3, 0);
    lv_obj_set_y(ui_Screen_Neopixel_Arc_Arc3, 40);
    lv_obj_set_align(ui_Screen_Neopixel_Arc_Arc3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen_Neopixel_Arc_Arc3, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_Screen_Neopixel_Arc_Arc3, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_arc_set_range(ui_Screen_Neopixel_Arc_Arc3, 0, 23);
    lv_arc_set_value(ui_Screen_Neopixel_Arc_Arc3, 0);
    lv_arc_set_bg_angles(ui_Screen_Neopixel_Arc_Arc3, 0, 360);
    lv_arc_set_rotation(ui_Screen_Neopixel_Arc_Arc3, 270);
    lv_obj_set_style_arc_width(ui_Screen_Neopixel_Arc_Arc3, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Screen_Neopixel_Arc_Arc3, lv_color_hex(0x00FF00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Screen_Neopixel_Arc_Arc3, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Screen_Neopixel_Arc_Arc3, 20, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Screen_Neopixel_Arc_Arc3, lv_color_hex(0x00FF00), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen_Neopixel_Arc_Arc3, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Screen_Neopixel_Switch_Switch1 = lv_switch_create(ui_Screen_Neopixel);
    lv_obj_set_width(ui_Screen_Neopixel_Switch_Switch1, 50);
    lv_obj_set_height(ui_Screen_Neopixel_Switch_Switch1, 25);
    lv_obj_set_x(ui_Screen_Neopixel_Switch_Switch1, 0);
    lv_obj_set_y(ui_Screen_Neopixel_Switch_Switch1, -83);
    lv_obj_set_align(ui_Screen_Neopixel_Switch_Switch1, LV_ALIGN_CENTER);


    lv_obj_add_event_cb(ui_Screen_Neopixel_Button_Button9, ui_event_Screen_Neopixel_Button_Button9, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen_Neopixel, ui_event_Screen_Neopixel, LV_EVENT_ALL, NULL);

}
