// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: MQOne

#include "../ui.h"

void ui_Screen_Demo_Widgets_screen_init(void)
{
    ui_Screen_Demo_Widgets = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen_Demo_Widgets, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_Screen_Demo_Widgets, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Screen_Demo_Widgets, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    ui_object_set_themeable_style_property(ui_Screen_Demo_Widgets, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Background);
    ui_object_set_themeable_style_property(ui_Screen_Demo_Widgets, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Background);

    ui_Screen_Demo_Widgets_Button_Button3 = lv_button_create(ui_Screen_Demo_Widgets);
    lv_obj_set_height(ui_Screen_Demo_Widgets_Button_Button3, 30);
    lv_obj_set_width(ui_Screen_Demo_Widgets_Button_Button3, lv_pct(90));
    lv_obj_set_x(ui_Screen_Demo_Widgets_Button_Button3, lv_pct(0));
    lv_obj_set_y(ui_Screen_Demo_Widgets_Button_Button3, lv_pct(-43));
    lv_obj_set_align(ui_Screen_Demo_Widgets_Button_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen_Demo_Widgets_Button_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Screen_Demo_Widgets_Button_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen_Demo_Widgets_Button_Button3, lv_color_hex(0x666563),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen_Demo_Widgets_Button_Button3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Screen_Demo_Widgets_Button_Button3, lv_color_hex(0x000000),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Screen_Demo_Widgets_Button_Button3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Screen_Demo_Widgets_Button_Button3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen_Demo_Widgets_Label_Label2 = lv_label_create(ui_Screen_Demo_Widgets_Button_Button3);
    lv_obj_set_width(ui_Screen_Demo_Widgets_Label_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen_Demo_Widgets_Label_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Screen_Demo_Widgets_Label_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen_Demo_Widgets_Label_Label2, "< Back");
    ui_object_set_themeable_style_property(ui_Screen_Demo_Widgets_Label_Label2, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_COLOR, _ui_theme_color_Font);
    ui_object_set_themeable_style_property(ui_Screen_Demo_Widgets_Label_Label2, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_OPA, _ui_theme_alpha_Font);
    lv_obj_set_style_text_font(ui_Screen_Demo_Widgets_Label_Label2, &lv_font_montserrat_20,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen_Demo_Widgets_Container_Container1 = lv_obj_create(ui_Screen_Demo_Widgets);
    lv_obj_remove_style_all(ui_Screen_Demo_Widgets_Container_Container1);
    lv_obj_set_height(ui_Screen_Demo_Widgets_Container_Container1, 128);
    lv_obj_set_width(ui_Screen_Demo_Widgets_Container_Container1, lv_pct(100));
    lv_obj_set_x(ui_Screen_Demo_Widgets_Container_Container1, -66);
    lv_obj_set_y(ui_Screen_Demo_Widgets_Container_Container1, -93);
    lv_obj_set_align(ui_Screen_Demo_Widgets_Container_Container1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Screen_Demo_Widgets_Container_Container1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Screen_Demo_Widgets_Container_Container1, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Screen_Demo_Widgets_Container_Container1,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Screen_Demo_Widgets_Arc_Arc2 = lv_arc_create(ui_Screen_Demo_Widgets_Container_Container1);
    lv_obj_set_width(ui_Screen_Demo_Widgets_Arc_Arc2, 100);
    lv_obj_set_height(ui_Screen_Demo_Widgets_Arc_Arc2, 100);
    lv_obj_set_x(ui_Screen_Demo_Widgets_Arc_Arc2, -50);
    lv_obj_set_y(ui_Screen_Demo_Widgets_Arc_Arc2, -46);
    lv_obj_set_align(ui_Screen_Demo_Widgets_Arc_Arc2, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_Screen_Demo_Widgets_Arc_Arc2, 50);

    ui_object_set_themeable_style_property(ui_Screen_Demo_Widgets_Arc_Arc2, LV_PART_INDICATOR | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_COLOR, _ui_theme_color_Background2);
    ui_object_set_themeable_style_property(ui_Screen_Demo_Widgets_Arc_Arc2, LV_PART_INDICATOR | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_OPA, _ui_theme_alpha_Background2);

    ui_object_set_themeable_style_property(ui_Screen_Demo_Widgets_Arc_Arc2, LV_PART_KNOB | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_COLOR, _ui_theme_color_Background2);
    ui_object_set_themeable_style_property(ui_Screen_Demo_Widgets_Arc_Arc2, LV_PART_KNOB | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_OPA, _ui_theme_alpha_Background2);

    ui_Screen_Demo_Widgets_Roller_Roller2 = lv_roller_create(ui_Screen_Demo_Widgets_Container_Container1);
    lv_roller_set_options(ui_Screen_Demo_Widgets_Roller_Roller2, "Option 1\nOption 2\nOption 3", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_height(ui_Screen_Demo_Widgets_Roller_Roller2, 100);
    lv_obj_set_width(ui_Screen_Demo_Widgets_Roller_Roller2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_Screen_Demo_Widgets_Roller_Roller2, 50);
    lv_obj_set_y(ui_Screen_Demo_Widgets_Roller_Roller2, -51);
    lv_obj_set_align(ui_Screen_Demo_Widgets_Roller_Roller2, LV_ALIGN_CENTER);

    lv_obj_set_style_radius(ui_Screen_Demo_Widgets_Roller_Roller2, 10, LV_PART_SELECTED | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Screen_Demo_Widgets_Roller_Roller2, LV_PART_SELECTED | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_COLOR, _ui_theme_color_Background2);
    ui_object_set_themeable_style_property(ui_Screen_Demo_Widgets_Roller_Roller2, LV_PART_SELECTED | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_OPA, _ui_theme_alpha_Background2);

    ui_Screen_Demo_Widgets_Slider_Slider1 = lv_slider_create(ui_Screen_Demo_Widgets);
    lv_slider_set_value(ui_Screen_Demo_Widgets_Slider_Slider1, 50, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Screen_Demo_Widgets_Slider_Slider1) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_Screen_Demo_Widgets_Slider_Slider1, 0, LV_ANIM_OFF);
    lv_obj_set_height(ui_Screen_Demo_Widgets_Slider_Slider1, 15);
    lv_obj_set_width(ui_Screen_Demo_Widgets_Slider_Slider1, lv_pct(80));
    lv_obj_set_x(ui_Screen_Demo_Widgets_Slider_Slider1, 4);
    lv_obj_set_y(ui_Screen_Demo_Widgets_Slider_Slider1, 24);
    lv_obj_set_align(ui_Screen_Demo_Widgets_Slider_Slider1, LV_ALIGN_CENTER);

    ui_object_set_themeable_style_property(ui_Screen_Demo_Widgets_Slider_Slider1, LV_PART_INDICATOR | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_COLOR, _ui_theme_color_Background2);
    ui_object_set_themeable_style_property(ui_Screen_Demo_Widgets_Slider_Slider1, LV_PART_INDICATOR | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_OPA, _ui_theme_alpha_Background2);

    ui_object_set_themeable_style_property(ui_Screen_Demo_Widgets_Slider_Slider1, LV_PART_KNOB | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_COLOR, _ui_theme_color_Background2);
    ui_object_set_themeable_style_property(ui_Screen_Demo_Widgets_Slider_Slider1, LV_PART_KNOB | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_OPA, _ui_theme_alpha_Background2);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Screen_Demo_Widgets_Slider_Slider1,
                                LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Screen_Demo_Widgets_Slider_Slider1,
                                                                                  lv_obj_get_style_pad_right(ui_Screen_Demo_Widgets_Slider_Slider1, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Screen_Demo_Widgets_Dropdown_Dropdown1 = lv_dropdown_create(ui_Screen_Demo_Widgets);
    lv_dropdown_set_options(ui_Screen_Demo_Widgets_Dropdown_Dropdown1, "Option 1\nOption 2\nOption 3");
    lv_obj_set_width(ui_Screen_Demo_Widgets_Dropdown_Dropdown1, lv_pct(50));
    lv_obj_set_height(ui_Screen_Demo_Widgets_Dropdown_Dropdown1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen_Demo_Widgets_Dropdown_Dropdown1, 2);
    lv_obj_set_y(ui_Screen_Demo_Widgets_Dropdown_Dropdown1, 113);
    lv_obj_set_align(ui_Screen_Demo_Widgets_Dropdown_Dropdown1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen_Demo_Widgets_Dropdown_Dropdown1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_object_set_themeable_style_property(lv_dropdown_get_list(ui_Screen_Demo_Widgets_Dropdown_Dropdown1),
                                           LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Background2);
    ui_object_set_themeable_style_property(lv_dropdown_get_list(ui_Screen_Demo_Widgets_Dropdown_Dropdown1),
                                           LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Background2);

    ui_Screen_Demo_Widgets_Container_Container2 = lv_obj_create(ui_Screen_Demo_Widgets);
    lv_obj_remove_style_all(ui_Screen_Demo_Widgets_Container_Container2);
    lv_obj_set_width(ui_Screen_Demo_Widgets_Container_Container2, lv_pct(100));
    lv_obj_set_height(ui_Screen_Demo_Widgets_Container_Container2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen_Demo_Widgets_Container_Container2, -24);
    lv_obj_set_y(ui_Screen_Demo_Widgets_Container_Container2, 90);
    lv_obj_set_align(ui_Screen_Demo_Widgets_Container_Container2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Screen_Demo_Widgets_Container_Container2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Screen_Demo_Widgets_Container_Container2, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Screen_Demo_Widgets_Container_Container2,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Screen_Demo_Widgets_Switch_Switch2 = lv_switch_create(ui_Screen_Demo_Widgets_Container_Container2);
    lv_obj_set_width(ui_Screen_Demo_Widgets_Switch_Switch2, 50);
    lv_obj_set_height(ui_Screen_Demo_Widgets_Switch_Switch2, 25);
    lv_obj_set_x(ui_Screen_Demo_Widgets_Switch_Switch2, 73);
    lv_obj_set_y(ui_Screen_Demo_Widgets_Switch_Switch2, 60);
    lv_obj_set_align(ui_Screen_Demo_Widgets_Switch_Switch2, LV_ALIGN_CENTER);

    ui_object_set_themeable_style_property(ui_Screen_Demo_Widgets_Switch_Switch2, LV_PART_KNOB | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_COLOR, _ui_theme_color_Background2);
    ui_object_set_themeable_style_property(ui_Screen_Demo_Widgets_Switch_Switch2, LV_PART_KNOB | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_OPA, _ui_theme_alpha_Background2);

    ui_Screen_Demo_Widgets_Checkbox_Checkbox1 = lv_checkbox_create(ui_Screen_Demo_Widgets_Container_Container2);
    lv_checkbox_set_text(ui_Screen_Demo_Widgets_Checkbox_Checkbox1, "Checkbox");
    lv_obj_set_width(ui_Screen_Demo_Widgets_Checkbox_Checkbox1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen_Demo_Widgets_Checkbox_Checkbox1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen_Demo_Widgets_Checkbox_Checkbox1, -44);
    lv_obj_set_y(ui_Screen_Demo_Widgets_Checkbox_Checkbox1, 63);
    lv_obj_set_align(ui_Screen_Demo_Widgets_Checkbox_Checkbox1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen_Demo_Widgets_Checkbox_Checkbox1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_Screen_Demo_Widgets_Checkbox_Checkbox1, lv_color_hex(0x000000),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen_Demo_Widgets_Checkbox_Checkbox1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_width(ui_Screen_Demo_Widgets_Checkbox_Checkbox1, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Screen_Demo_Widgets_Button_Button3, ui_event_Screen_Demo_Widgets_Button_Button3, LV_EVENT_ALL,
                        NULL);

}
