// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: MQOne

#include "../ui.h"

void ui_Screen_Menu_screen_init(void)
{
    ui_Screen_Menu = lv_obj_create(NULL);
    lv_obj_set_flex_flow(ui_Screen_Menu, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Screen_Menu, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    ui_object_set_themeable_style_property(ui_Screen_Menu, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Background);
    ui_object_set_themeable_style_property(ui_Screen_Menu, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Background);
    lv_obj_set_style_pad_left(ui_Screen_Menu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Screen_Menu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Screen_Menu, 18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Screen_Menu, 18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_opa(ui_Screen_Menu, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Screen_Menu_Menubutton_MenuButton8 = ui_Button_MenuButton_create(ui_Screen_Menu);
    lv_obj_set_x(ui_Screen_Menu_Menubutton_MenuButton8, -53);
    lv_obj_set_y(ui_Screen_Menu_Menubutton_MenuButton8, -168);
    lv_obj_add_flag(ui_Screen_Menu_Menubutton_MenuButton8, LV_OBJ_FLAG_HIDDEN);     /// Flags

    lv_label_set_text(ui_comp_get_child(ui_Screen_Menu_Menubutton_MenuButton8, UI_COMP_BUTTON_MENUBUTTON_LABEL_LABEL3),
                      "Dev Module");

    ui_Screen_Menu_Menubutton_MenuButton7 = ui_Button_MenuButton_create(ui_Screen_Menu);
    lv_obj_set_x(ui_Screen_Menu_Menubutton_MenuButton7, -53);
    lv_obj_set_y(ui_Screen_Menu_Menubutton_MenuButton7, -168);
    lv_obj_add_flag(ui_Screen_Menu_Menubutton_MenuButton7, LV_OBJ_FLAG_HIDDEN);     /// Flags

    lv_label_set_text(ui_comp_get_child(ui_Screen_Menu_Menubutton_MenuButton7, UI_COMP_BUTTON_MENUBUTTON_LABEL_LABEL3),
                      "Mount Mod");

    ui_Screen_Menu_Menubutton_MenuButton6 = ui_Button_MenuButton_create(ui_Screen_Menu);
    lv_obj_set_x(ui_Screen_Menu_Menubutton_MenuButton6, -53);
    lv_obj_set_y(ui_Screen_Menu_Menubutton_MenuButton6, -168);
    lv_obj_add_flag(ui_Screen_Menu_Menubutton_MenuButton6, LV_OBJ_FLAG_HIDDEN);     /// Flags

    lv_label_set_text(ui_comp_get_child(ui_Screen_Menu_Menubutton_MenuButton6, UI_COMP_BUTTON_MENUBUTTON_LABEL_LABEL3),
                      "Camera Mod");

    ui_Screen_Menu_Menubutton_MenuButton = ui_Button_MenuButton_create(ui_Screen_Menu);
    lv_obj_set_x(ui_Screen_Menu_Menubutton_MenuButton, -53);
    lv_obj_set_y(ui_Screen_Menu_Menubutton_MenuButton, -168);

    ui_Screen_Menu_Menubutton_MenuButton1 = ui_Button_MenuButton_create(ui_Screen_Menu);
    lv_obj_set_x(ui_Screen_Menu_Menubutton_MenuButton1, -53);
    lv_obj_set_y(ui_Screen_Menu_Menubutton_MenuButton1, -168);

    lv_label_set_text(ui_comp_get_child(ui_Screen_Menu_Menubutton_MenuButton1, UI_COMP_BUTTON_MENUBUTTON_LABEL_LABEL3),
                      "Power CTRL");

    ui_Screen_Menu_Menubutton_MenuButton3 = ui_Button_MenuButton_create(ui_Screen_Menu);
    lv_obj_set_x(ui_Screen_Menu_Menubutton_MenuButton3, -53);
    lv_obj_set_y(ui_Screen_Menu_Menubutton_MenuButton3, -168);

    lv_label_set_text(ui_comp_get_child(ui_Screen_Menu_Menubutton_MenuButton3, UI_COMP_BUTTON_MENUBUTTON_LABEL_LABEL3),
                      "NeoPixels");

    ui_Screen_Menu_Menubutton_MenuButton4 = ui_Button_MenuButton_create(ui_Screen_Menu);
    lv_obj_set_x(ui_Screen_Menu_Menubutton_MenuButton4, -53);
    lv_obj_set_y(ui_Screen_Menu_Menubutton_MenuButton4, -168);

    lv_label_set_text(ui_comp_get_child(ui_Screen_Menu_Menubutton_MenuButton4, UI_COMP_BUTTON_MENUBUTTON_LABEL_LABEL3),
                      "microSD");

    ui_Screen_Menu_Menubutton_MenuButton2 = ui_Button_MenuButton_create(ui_Screen_Menu);
    lv_obj_set_x(ui_Screen_Menu_Menubutton_MenuButton2, -53);
    lv_obj_set_y(ui_Screen_Menu_Menubutton_MenuButton2, -168);

    lv_label_set_text(ui_comp_get_child(ui_Screen_Menu_Menubutton_MenuButton2, UI_COMP_BUTTON_MENUBUTTON_LABEL_LABEL3),
                      "IMU");

    lv_obj_add_event_cb(ui_Screen_Menu_Menubutton_MenuButton8,
                        ui_event_Screen_Menu_Menubutton_MenuButton8_Button_MenuButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen_Menu_Menubutton_MenuButton7,
                        ui_event_Screen_Menu_Menubutton_MenuButton7_Button_MenuButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen_Menu_Menubutton_MenuButton6,
                        ui_event_Screen_Menu_Menubutton_MenuButton6_Button_MenuButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen_Menu_Menubutton_MenuButton, ui_event_Screen_Menu_Menubutton_MenuButton_Button_MenuButton,
                        LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen_Menu_Menubutton_MenuButton1,
                        ui_event_Screen_Menu_Menubutton_MenuButton1_Button_MenuButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen_Menu_Menubutton_MenuButton3,
                        ui_event_Screen_Menu_Menubutton_MenuButton3_Button_MenuButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen_Menu_Menubutton_MenuButton4,
                        ui_event_Screen_Menu_Menubutton_MenuButton4_Button_MenuButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen_Menu_Menubutton_MenuButton2,
                        ui_event_Screen_Menu_Menubutton_MenuButton2_Button_MenuButton, LV_EVENT_ALL, NULL);

}
