// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: MQOne

#include "../ui.h"

void ui_Screen_Power_screen_init(void)
{
    ui_Screen_Power = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen_Power, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_Screen_Power, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Screen_Power, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    ui_object_set_themeable_style_property(ui_Screen_Power, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Background);
    ui_object_set_themeable_style_property(ui_Screen_Power, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Background);

    ui_Screen_Power_Button_Button4 = lv_button_create(ui_Screen_Power);
    lv_obj_set_height(ui_Screen_Power_Button_Button4, 30);
    lv_obj_set_width(ui_Screen_Power_Button_Button4, lv_pct(90));
    lv_obj_set_x(ui_Screen_Power_Button_Button4, lv_pct(0));
    lv_obj_set_y(ui_Screen_Power_Button_Button4, lv_pct(-43));
    lv_obj_set_align(ui_Screen_Power_Button_Button4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen_Power_Button_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Screen_Power_Button_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen_Power_Button_Button4, lv_color_hex(0x666563), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen_Power_Button_Button4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Screen_Power_Button_Button4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Screen_Power_Button_Button4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Screen_Power_Button_Button4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen_Power_Label_Label5 = lv_label_create(ui_Screen_Power_Button_Button4);
    lv_obj_set_width(ui_Screen_Power_Label_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen_Power_Label_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Screen_Power_Label_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen_Power_Label_Label5, "< Back");
    ui_object_set_themeable_style_property(ui_Screen_Power_Label_Label5, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_COLOR, _ui_theme_color_Font);
    ui_object_set_themeable_style_property(ui_Screen_Power_Label_Label5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Font);
    lv_obj_set_style_text_font(ui_Screen_Power_Label_Label5, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen_Power_Menubutton_MenuButton5 = ui_Button_MenuButton_create(ui_Screen_Power);
    lv_obj_set_width(ui_Screen_Power_Menubutton_MenuButton5, lv_pct(90));
    lv_obj_set_height(ui_Screen_Power_Menubutton_MenuButton5, lv_pct(30));
    lv_obj_set_x(ui_Screen_Power_Menubutton_MenuButton5, 9);
    lv_obj_set_y(ui_Screen_Power_Menubutton_MenuButton5, 18);
    lv_obj_set_style_bg_color(ui_Screen_Power_Menubutton_MenuButton5, lv_color_hex(0xFF0000),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen_Power_Menubutton_MenuButton5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_label_set_text(ui_comp_get_child(ui_Screen_Power_Menubutton_MenuButton5, UI_COMP_BUTTON_MENUBUTTON_LABEL_LABEL3),
                      "Shut Down");

    lv_obj_add_event_cb(ui_Screen_Power_Button_Button4, ui_event_Screen_Power_Button_Button4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen_Power_Menubutton_MenuButton5,
                        ui_event_Screen_Power_Menubutton_MenuButton5_Button_MenuButton, LV_EVENT_ALL, NULL);

}
