// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: MQOne

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void appear_Animation(lv_obj_t * TargetObject, int delay);
void load_Animation(lv_obj_t * TargetObject, int delay);


// SCREEN: ui_Screen_Start_App
void ui_Screen_Start_App_screen_init(void);
void ui_event_Screen_Start_App(lv_event_t * e);
lv_obj_t * ui_Screen_Start_App;
lv_obj_t * ui_Screen_Start_App_Image_MQLogo;
lv_obj_t * ui_Screen_Start_App_Spinner_Load;
void ui_event_Screen_Start_App_Button_Button2(lv_event_t * e);
lv_obj_t * ui_Screen_Start_App_Button_Button2;
lv_obj_t * ui_Screen_Start_App_Label_Label1;


// SCREEN: ui_Screen_Menu
void ui_Screen_Menu_screen_init(void);
lv_obj_t * ui_Screen_Menu;
void ui_event_Screen_Menu_Menubutton_MenuButton8_Button_MenuButton(lv_event_t * e);
lv_obj_t * ui_Screen_Menu_Menubutton_MenuButton8;
void ui_event_Screen_Menu_Menubutton_MenuButton7_Button_MenuButton(lv_event_t * e);
lv_obj_t * ui_Screen_Menu_Menubutton_MenuButton7;
void ui_event_Screen_Menu_Menubutton_MenuButton6_Button_MenuButton(lv_event_t * e);
lv_obj_t * ui_Screen_Menu_Menubutton_MenuButton6;
void ui_event_Screen_Menu_Menubutton_MenuButton_Button_MenuButton(lv_event_t * e);
lv_obj_t * ui_Screen_Menu_Menubutton_MenuButton;
void ui_event_Screen_Menu_Menubutton_MenuButton1_Button_MenuButton(lv_event_t * e);
lv_obj_t * ui_Screen_Menu_Menubutton_MenuButton1;
void ui_event_Screen_Menu_Menubutton_MenuButton3_Button_MenuButton(lv_event_t * e);
lv_obj_t * ui_Screen_Menu_Menubutton_MenuButton3;
void ui_event_Screen_Menu_Menubutton_MenuButton4_Button_MenuButton(lv_event_t * e);
lv_obj_t * ui_Screen_Menu_Menubutton_MenuButton4;
void ui_event_Screen_Menu_Menubutton_MenuButton2_Button_MenuButton(lv_event_t * e);
lv_obj_t * ui_Screen_Menu_Menubutton_MenuButton2;


// SCREEN: ui_Screen_Demo_Widgets
void ui_Screen_Demo_Widgets_screen_init(void);
lv_obj_t * ui_Screen_Demo_Widgets;
void ui_event_Screen_Demo_Widgets_Button_Button3(lv_event_t * e);
lv_obj_t * ui_Screen_Demo_Widgets_Button_Button3;
lv_obj_t * ui_Screen_Demo_Widgets_Label_Label2;
lv_obj_t * ui_Screen_Demo_Widgets_Container_Container1;
lv_obj_t * ui_Screen_Demo_Widgets_Arc_Arc2;
lv_obj_t * ui_Screen_Demo_Widgets_Roller_Roller2;
lv_obj_t * ui_Screen_Demo_Widgets_Slider_Slider1;
lv_obj_t * ui_Screen_Demo_Widgets_Dropdown_Dropdown1;
lv_obj_t * ui_Screen_Demo_Widgets_Container_Container2;
lv_obj_t * ui_Screen_Demo_Widgets_Switch_Switch2;
lv_obj_t * ui_Screen_Demo_Widgets_Checkbox_Checkbox1;


// SCREEN: ui_Screen_Power
void ui_Screen_Power_screen_init(void);
lv_obj_t * ui_Screen_Power;
void ui_event_Screen_Power_Button_Button4(lv_event_t * e);
lv_obj_t * ui_Screen_Power_Button_Button4;
lv_obj_t * ui_Screen_Power_Label_Label5;
void ui_event_Screen_Power_Menubutton_MenuButton5_Button_MenuButton(lv_event_t * e);
lv_obj_t * ui_Screen_Power_Menubutton_MenuButton5;


// SCREEN: ui_Camera_Module
void ui_Camera_Module_screen_init(void);
void ui_event_Camera_Module(lv_event_t * e);
lv_obj_t * ui_Camera_Module;
void ui_event_Camera_Module_Button_Button5(lv_event_t * e);
lv_obj_t * ui_Camera_Module_Button_Button5;
lv_obj_t * ui_Camera_Module_Label_Label6;


// SCREEN: ui_Dev_Module
void ui_Dev_Module_screen_init(void);
lv_obj_t * ui_Dev_Module;
void ui_event_Dev_Module_Button_Button7(lv_event_t * e);
lv_obj_t * ui_Dev_Module_Button_Button7;
lv_obj_t * ui_Dev_Module_Label_Label8;
lv_obj_t * ui_Dev_Module_Panel_Panel1;
lv_obj_t * ui_Dev_Module_Label_Label11;


// SCREEN: ui_Mountain_Module
void ui_Mountain_Module_screen_init(void);
void ui_event_Mountain_Module(lv_event_t * e);
lv_obj_t * ui_Mountain_Module;
void ui_event_Mountain_Module_Button_Button6(lv_event_t * e);
lv_obj_t * ui_Mountain_Module_Button_Button6;
lv_obj_t * ui_Mountain_Module_Label_Label7;
lv_obj_t * ui_Mountain_Module_Image_Image5;
lv_obj_t * ui_Mountain_Module_Container_Container3;
lv_obj_t * ui_Mountain_Module_Label_Label9;
lv_obj_t * ui_Mountain_Module_Label_Label12;
lv_obj_t * ui_Mountain_Module_Label_Label13;
lv_obj_t * ui_Mountain_Module_Container_Container4;
lv_obj_t * ui_Mountain_Module_Label_Label10;
lv_obj_t * ui_Mountain_Module_Label_Label14;
lv_obj_t * ui_Mountain_Module_Label_Label15;
lv_obj_t * ui_Mountain_Module_Container_Container7;
lv_obj_t * ui_Mountain_Module_Label_Label4;
lv_obj_t * ui_Mountain_Module_Label_Label18;
lv_obj_t * ui_Mountain_Module_Container_Container5;
lv_obj_t * ui_Mountain_Module_Container_Container8;
lv_obj_t * ui_Mountain_Module_Label_Label16;
lv_obj_t * ui_Mountain_Module_Label_Label20;
lv_obj_t * ui_Mountain_Module_Container_Container9;
lv_obj_t * ui_Mountain_Module_Label_Label21;
lv_obj_t * ui_Mountain_Module_Label_Label22;


// SCREEN: ui_Screen_IMU
void ui_Screen_IMU_screen_init(void);
void ui_event_Screen_IMU(lv_event_t * e);
lv_obj_t * ui_Screen_IMU;
void ui_event_Screen_IMU_Button_Button8(lv_event_t * e);
lv_obj_t * ui_Screen_IMU_Button_Button8;
lv_obj_t * ui_Screen_IMU_Label_Label17;


// SCREEN: ui_Screen_Neopixel
void ui_Screen_Neopixel_screen_init(void);
void ui_event_Screen_Neopixel(lv_event_t * e);
lv_obj_t * ui_Screen_Neopixel;
void ui_event_Screen_Neopixel_Button_Button9(lv_event_t * e);
lv_obj_t * ui_Screen_Neopixel_Button_Button9;
lv_obj_t * ui_Screen_Neopixel_Label_Label23;
lv_obj_t * ui_Screen_Neopixel_Arc_Arc1;
lv_obj_t * ui_Screen_Neopixel_Arc_Arc3;
lv_obj_t * ui_Screen_Neopixel_Switch_Switch1;


// SCREEN: ui_Screen_microSD
void ui_Screen_microSD_screen_init(void);
void ui_event_Screen_microSD(lv_event_t * e);
lv_obj_t * ui_Screen_microSD;
void ui_event_Screen_microSD_Button_Button10(lv_event_t * e);
lv_obj_t * ui_Screen_microSD_Button_Button10;
lv_obj_t * ui_Screen_microSD_Label_Label24;
lv_obj_t * ui_Startevents____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void appear_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 500);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_y);
    lv_anim_set_values(&PropertyAnimation_0, 300, -30);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_ease_in);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);
    ui_anim_user_data_t * PropertyAnimation_1_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_1_user_data->target = TargetObject;
    PropertyAnimation_1_user_data->val = -1;
    lv_anim_t PropertyAnimation_1;
    lv_anim_init(&PropertyAnimation_1);
    lv_anim_set_time(&PropertyAnimation_1, 500);
    lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_y);
    lv_anim_set_values(&PropertyAnimation_1, -30, -200);
    lv_anim_set_path_cb(&PropertyAnimation_1, lv_anim_path_ease_out);
    lv_anim_set_delay(&PropertyAnimation_1, delay + 2500);
    lv_anim_set_deleted_cb(&PropertyAnimation_1, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_1, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_1, 0);
    lv_anim_set_early_apply(&PropertyAnimation_1, false);
    lv_anim_start(&PropertyAnimation_1);

}
void load_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 500);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_opacity);
    lv_anim_set_values(&PropertyAnimation_0, 0, 255);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_ease_in_out);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 500);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);
    ui_anim_user_data_t * PropertyAnimation_1_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_1_user_data->target = TargetObject;
    PropertyAnimation_1_user_data->val = -1;
    lv_anim_t PropertyAnimation_1;
    lv_anim_init(&PropertyAnimation_1);
    lv_anim_set_time(&PropertyAnimation_1, 500);
    lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_opacity);
    lv_anim_set_values(&PropertyAnimation_1, 255, 0);
    lv_anim_set_path_cb(&PropertyAnimation_1, lv_anim_path_ease_in_out);
    lv_anim_set_delay(&PropertyAnimation_1, delay + 2500);
    lv_anim_set_deleted_cb(&PropertyAnimation_1, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_1, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_1, 0);
    lv_anim_set_early_apply(&PropertyAnimation_1, false);
    lv_anim_start(&PropertyAnimation_1);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_Screen_Start_App(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        lv_app_start_load_screen(e);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOADED) {
        lv_app_start_unload_screen(e);
    }
}
void ui_event_Screen_Start_App_Button_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen_Menu, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen_Menu_screen_init);
    }
}
void ui_event_Screen_Menu_Menubutton_MenuButton8_Button_MenuButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Dev_Module, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Dev_Module_screen_init);
    }
}
void ui_event_Screen_Menu_Menubutton_MenuButton7_Button_MenuButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Mountain_Module, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Mountain_Module_screen_init);
    }
}
void ui_event_Screen_Menu_Menubutton_MenuButton6_Button_MenuButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Camera_Module, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Camera_Module_screen_init);
    }
}
void ui_event_Screen_Menu_Menubutton_MenuButton_Button_MenuButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen_Demo_Widgets, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen_Demo_Widgets_screen_init);
    }
}
void ui_event_Screen_Menu_Menubutton_MenuButton1_Button_MenuButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen_Power, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen_Power_screen_init);
    }
}
void ui_event_Screen_Menu_Menubutton_MenuButton3_Button_MenuButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen_Neopixel, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen_Neopixel_screen_init);
    }
}
void ui_event_Screen_Menu_Menubutton_MenuButton4_Button_MenuButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen_microSD, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen_microSD_screen_init);
    }
}
void ui_event_Screen_Menu_Menubutton_MenuButton2_Button_MenuButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen_IMU, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen_IMU_screen_init);
    }
}
void ui_event_Screen_Demo_Widgets_Button_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen_Menu, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen_Menu_screen_init);
    }
}
void ui_event_Screen_Power_Button_Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen_Menu, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen_Menu_screen_init);
    }
}
void ui_event_Screen_Power_Menubutton_MenuButton5_Button_MenuButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        lv_shut_down_device(e);
    }
}
void ui_event_Camera_Module(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        lv_camera_module_load_screen(e);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOADED) {
        lv_camera_module_unload_screen(e);
    }
}
void ui_event_Camera_Module_Button_Button5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen_Menu, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen_Menu_screen_init);
    }
}
void ui_event_Dev_Module_Button_Button7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen_Menu, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen_Menu_screen_init);
    }
}
void ui_event_Mountain_Module(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        lv_mountain_module_load_screen(e);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOADED) {
        lv_mountain_module_unload_screen(e);
    }
}
void ui_event_Mountain_Module_Button_Button6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen_Menu, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen_Menu_screen_init);
    }
}
void ui_event_Screen_IMU(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        lv_imu_load_screen(e);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOADED) {
        lv_imu_unload_screen(e);
    }
}
void ui_event_Screen_IMU_Button_Button8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen_Menu, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen_Menu_screen_init);
    }
}
void ui_event_Screen_Neopixel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        lv_neopixel_load_screen(e);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOADED) {
        lv_neopixel_unload_screen(e);
    }
}
void ui_event_Screen_Neopixel_Button_Button9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen_Menu, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen_Menu_screen_init);
    }
}
void ui_event_Screen_microSD(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        lv_microsd_load_screen(e);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOADED) {
        lv_microsd_unload_screen(e);
    }
}
void ui_event_Screen_microSD_Button_Button10(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen_Menu, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen_Menu_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

    lv_disp_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen_Start_App_screen_init();
    ui_Screen_Menu_screen_init();
    ui_Screen_Demo_Widgets_screen_init();
    ui_Screen_Power_screen_init();
    ui_Camera_Module_screen_init();
    ui_Dev_Module_screen_init();
    ui_Mountain_Module_screen_init();
    ui_Screen_IMU_screen_init();
    ui_Screen_Neopixel_screen_init();
    ui_Screen_microSD_screen_init();
    ui_Startevents____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen_Start_App);
}
