// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: MQOne

#ifndef _MQONE_UI_H
#define _MQONE_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"

void appear_Animation(lv_obj_t * TargetObject, int delay);
void load_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_Screen_Start_App
void ui_Screen_Start_App_screen_init(void);
void ui_event_Screen_Start_App(lv_event_t * e);
extern lv_obj_t * ui_Screen_Start_App;
extern lv_obj_t * ui_Screen_Start_App_Image_MQLogo;
extern lv_obj_t * ui_Screen_Start_App_Spinner_Load;
void ui_event_Screen_Start_App_Button_Button2(lv_event_t * e);
extern lv_obj_t * ui_Screen_Start_App_Button_Button2;
extern lv_obj_t * ui_Screen_Start_App_Label_Label1;
// SCREEN: ui_Screen_Menu
void ui_Screen_Menu_screen_init(void);
extern lv_obj_t * ui_Screen_Menu;
void ui_event_Screen_Menu_Menubutton_MenuButton8_Button_MenuButton(lv_event_t * e);
extern lv_obj_t * ui_Screen_Menu_Menubutton_MenuButton8;
void ui_event_Screen_Menu_Menubutton_MenuButton7_Button_MenuButton(lv_event_t * e);
extern lv_obj_t * ui_Screen_Menu_Menubutton_MenuButton7;
void ui_event_Screen_Menu_Menubutton_MenuButton6_Button_MenuButton(lv_event_t * e);
extern lv_obj_t * ui_Screen_Menu_Menubutton_MenuButton6;
void ui_event_Screen_Menu_Menubutton_MenuButton_Button_MenuButton(lv_event_t * e);
extern lv_obj_t * ui_Screen_Menu_Menubutton_MenuButton;
void ui_event_Screen_Menu_Menubutton_MenuButton1_Button_MenuButton(lv_event_t * e);
extern lv_obj_t * ui_Screen_Menu_Menubutton_MenuButton1;
void ui_event_Screen_Menu_Menubutton_MenuButton3_Button_MenuButton(lv_event_t * e);
extern lv_obj_t * ui_Screen_Menu_Menubutton_MenuButton3;
void ui_event_Screen_Menu_Menubutton_MenuButton4_Button_MenuButton(lv_event_t * e);
extern lv_obj_t * ui_Screen_Menu_Menubutton_MenuButton4;
void ui_event_Screen_Menu_Menubutton_MenuButton2_Button_MenuButton(lv_event_t * e);
extern lv_obj_t * ui_Screen_Menu_Menubutton_MenuButton2;
// SCREEN: ui_Screen_Demo_Widgets
void ui_Screen_Demo_Widgets_screen_init(void);
extern lv_obj_t * ui_Screen_Demo_Widgets;
void ui_event_Screen_Demo_Widgets_Button_Button3(lv_event_t * e);
extern lv_obj_t * ui_Screen_Demo_Widgets_Button_Button3;
extern lv_obj_t * ui_Screen_Demo_Widgets_Label_Label2;
extern lv_obj_t * ui_Screen_Demo_Widgets_Container_Container1;
extern lv_obj_t * ui_Screen_Demo_Widgets_Arc_Arc2;
extern lv_obj_t * ui_Screen_Demo_Widgets_Roller_Roller2;
extern lv_obj_t * ui_Screen_Demo_Widgets_Slider_Slider1;
extern lv_obj_t * ui_Screen_Demo_Widgets_Dropdown_Dropdown1;
extern lv_obj_t * ui_Screen_Demo_Widgets_Container_Container2;
extern lv_obj_t * ui_Screen_Demo_Widgets_Switch_Switch2;
extern lv_obj_t * ui_Screen_Demo_Widgets_Checkbox_Checkbox1;
// SCREEN: ui_Screen_Power
void ui_Screen_Power_screen_init(void);
extern lv_obj_t * ui_Screen_Power;
void ui_event_Screen_Power_Button_Button4(lv_event_t * e);
extern lv_obj_t * ui_Screen_Power_Button_Button4;
extern lv_obj_t * ui_Screen_Power_Label_Label5;
void ui_event_Screen_Power_Menubutton_MenuButton5_Button_MenuButton(lv_event_t * e);
extern lv_obj_t * ui_Screen_Power_Menubutton_MenuButton5;
// SCREEN: ui_Camera_Module
void ui_Camera_Module_screen_init(void);
void ui_event_Camera_Module(lv_event_t * e);
extern lv_obj_t * ui_Camera_Module;
void ui_event_Camera_Module_Button_Button5(lv_event_t * e);
extern lv_obj_t * ui_Camera_Module_Button_Button5;
extern lv_obj_t * ui_Camera_Module_Label_Label6;
// SCREEN: ui_Dev_Module
void ui_Dev_Module_screen_init(void);
extern lv_obj_t * ui_Dev_Module;
void ui_event_Dev_Module_Button_Button7(lv_event_t * e);
extern lv_obj_t * ui_Dev_Module_Button_Button7;
extern lv_obj_t * ui_Dev_Module_Label_Label8;
extern lv_obj_t * ui_Dev_Module_Panel_Panel1;
extern lv_obj_t * ui_Dev_Module_Label_Label11;
// SCREEN: ui_Mountain_Module
void ui_Mountain_Module_screen_init(void);
void ui_event_Mountain_Module(lv_event_t * e);
extern lv_obj_t * ui_Mountain_Module;
void ui_event_Mountain_Module_Button_Button6(lv_event_t * e);
extern lv_obj_t * ui_Mountain_Module_Button_Button6;
extern lv_obj_t * ui_Mountain_Module_Label_Label7;
extern lv_obj_t * ui_Mountain_Module_Image_Image5;
extern lv_obj_t * ui_Mountain_Module_Container_Container3;
extern lv_obj_t * ui_Mountain_Module_Label_Label9;
extern lv_obj_t * ui_Mountain_Module_Label_Label12;
extern lv_obj_t * ui_Mountain_Module_Label_Label13;
extern lv_obj_t * ui_Mountain_Module_Container_Container4;
extern lv_obj_t * ui_Mountain_Module_Label_Label10;
extern lv_obj_t * ui_Mountain_Module_Label_Label14;
extern lv_obj_t * ui_Mountain_Module_Label_Label15;
extern lv_obj_t * ui_Mountain_Module_Container_Container7;
extern lv_obj_t * ui_Mountain_Module_Label_Label4;
extern lv_obj_t * ui_Mountain_Module_Label_Label18;
extern lv_obj_t * ui_Mountain_Module_Container_Container5;
extern lv_obj_t * ui_Mountain_Module_Container_Container8;
extern lv_obj_t * ui_Mountain_Module_Label_Label16;
extern lv_obj_t * ui_Mountain_Module_Label_Label20;
extern lv_obj_t * ui_Mountain_Module_Container_Container9;
extern lv_obj_t * ui_Mountain_Module_Label_Label21;
extern lv_obj_t * ui_Mountain_Module_Label_Label22;
// SCREEN: ui_Screen_IMU
void ui_Screen_IMU_screen_init(void);
void ui_event_Screen_IMU(lv_event_t * e);
extern lv_obj_t * ui_Screen_IMU;
void ui_event_Screen_IMU_Button_Button8(lv_event_t * e);
extern lv_obj_t * ui_Screen_IMU_Button_Button8;
extern lv_obj_t * ui_Screen_IMU_Label_Label17;
// SCREEN: ui_Screen_Neopixel
void ui_Screen_Neopixel_screen_init(void);
void ui_event_Screen_Neopixel(lv_event_t * e);
extern lv_obj_t * ui_Screen_Neopixel;
void ui_event_Screen_Neopixel_Button_Button9(lv_event_t * e);
extern lv_obj_t * ui_Screen_Neopixel_Button_Button9;
extern lv_obj_t * ui_Screen_Neopixel_Label_Label23;
extern lv_obj_t * ui_Screen_Neopixel_Arc_Arc1;
extern lv_obj_t * ui_Screen_Neopixel_Arc_Arc3;
extern lv_obj_t * ui_Screen_Neopixel_Switch_Switch1;
// SCREEN: ui_Screen_microSD
void ui_Screen_microSD_screen_init(void);
void ui_event_Screen_microSD(lv_event_t * e);
extern lv_obj_t * ui_Screen_microSD;
void ui_event_Screen_microSD_Button_Button10(lv_event_t * e);
extern lv_obj_t * ui_Screen_microSD_Button_Button10;
extern lv_obj_t * ui_Screen_microSD_Label_Label24;
extern lv_obj_t * ui_Startevents____initial_actions0;


LV_IMG_DECLARE(ui_img_mq_png);    // assets/MQ.png
LV_IMG_DECLARE(ui_img_sat_png);    // assets/sat.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
