// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: MQOne

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void lv_app_start_load_screen(lv_event_t * e);
void lv_app_start_unload_screen(lv_event_t * e);
void lv_shut_down_device(lv_event_t * e);
void lv_camera_module_load_screen(lv_event_t * e);
void lv_camera_module_unload_screen(lv_event_t * e);
void lv_mountain_module_load_screen(lv_event_t * e);
void lv_mountain_module_unload_screen(lv_event_t * e);
void lv_imu_load_screen(lv_event_t * e);
void lv_imu_unload_screen(lv_event_t * e);
void lv_neopixel_load_screen(lv_event_t * e);
void lv_neopixel_unload_screen(lv_event_t * e);
void lv_microsd_load_screen(lv_event_t * e);
void lv_microsd_unload_screen(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
