// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: MQOne

#include "ui.h"


const ui_theme_variable_t _ui_theme_color_Background[2] = {0xFFF3DC, 0x202020};
const ui_theme_variable_t _ui_theme_alpha_Background[2] = {255, 255};

const ui_theme_variable_t _ui_theme_color_Background2[2] = {0xFFAA00, 0xFFAA00};
const ui_theme_variable_t _ui_theme_alpha_Background2[2] = {255, 255};

const ui_theme_variable_t _ui_theme_color_Font[2] = {0xFFFFFF, 0xFFFFFF};
const ui_theme_variable_t _ui_theme_alpha_Font[2] = {255, 255};
uint8_t ui_theme_idx = UI_THEME_DARK;


void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

